行き詰まりました。。
yuya-konkon/04_select pull request #3
Opened 2020-01-29 14:07 UTC by yuya-konkon

【現時点】
とりあえず画像と同じになるように検索を入れた
【現在うまくいっていない点】
入力しても反応しない
【試したこと】
if文を使って入れてみたましたが、うまく表示されなくてエラーになる

【認識】
今回はhtmlのなかにフォームを作って、検索→中身は、if文を使って検索したら、それに該当するデータが帰ってくる。入力しないと全文出る
「if(id, tyoe~) else (全文みたいな？？)」

2020-01-29 14:32 UTC, Arisaarisa commented on search.php
> +
select.phpとsearch.phpとありますかね？
select.phpのファイルのみで完結できます！
likeでとってくる場合ですが、
ヒントにあるように
直してみてください！
GETメソッドにlikeでも利用する変数を設定したのち、
if,elseで条件分岐
するイメージです！
わかりそうですか？

2020-01-29 14:49 UTC, Arisaarisa commented on search.php
> +
とその前に$_SERVER変数でリクエストのメソッドも追加が必要なので
カリキュラムの10もチェックしてみてください！

2020-01-29 14:54 UTC, Arisaarisa commented on search.php
> +
<li>$_SERVER変数でリクエストのメソッド追加
<li>GETメソッド
<li>条件分岐でlike
という流れです！

2020-02-01 14:47 UTC, kazu-taka requested changes

2020-02-01 14:47 UTC, kazu-taka commented on select.php
> +}
@yuya-konkon 
まずはif文全体を見てみて下さい！
私がヒントで書いた文章は、キーワードが設定されているか、されていないかでif、elseが切り替わるようになっています。
近藤さんのコードは、REQUEST_METHODがGETなのかそれ以外で処理が変わってしまっています。
もう一度ifの部分を整理してみて下さい。
```php
if (($_SERVER['REQUEST_METHOD']) === 'GET') {

  // キーワードを変数に代入
  $keyword = $_GET['keyword'];
  // もし変数(キーワード)が空の場合
  if ($keyword == '') {
    // animalsテーブルから全件データを取得し変数(配列)に代入
  }

} else {
  // キーワードが空以外の場合
  // animalsテーブルからキーワードを含んだデータのみをlikeで取得し変数(配列)に代入
}
```

2020-02-01 14:52 UTC, kazu-taka commented on select.php
> +}
if文を分かりやすくするために、コードの一部を省略してます！

2020-02-01 15:04 UTC, yuya-konkon commented on select.php
> +}
確認ありがとうございます！
今日は頭がうまく働かないので寝ます🤯
がんばります

2020-02-03 01:58 UTC, Arisaarisa commented on select.php
> +  }
ここで閉じるとルール的によくないので
if elseをきちんと中に入れた状態で閉じます！
if と elseのインデントも揃えてください。

2020-02-03 02:02 UTC, Arisaarisa commented on select.php
> +  $sql = "select * from animals where description like '%$keyword%' ";
直接文字列を習得するのはPHP的にあまり良くないので
バインドParamsを使った形式に修正してください！
https://23seiki.gitbook.io/php/php/09#2-2-2-puripeadosuttomentotopursuhorudaniyorurishi

2020-02-03 02:05 UTC, Arisaarisa commented
確認しました！修正お願いします！
<li>}の閉じる位置
<li>if,elseインデントの修正
<li>バインドパラムスの使用

2020-02-03 06:10 UTC, yuya-konkon commented
課題終わりました。
確認お願い致します。

<img width="952" alt="スクリーンショット 2020-02-03 15 09 46" src="https://user-images.githubusercontent.com/58411049/73629682-43387180-4697-11ea-8a19-42d41000dcbe.png">
<img width="952" alt="スクリーンショット 2020-02-03 15 09 52" src="https://user-images.githubusercontent.com/58411049/73629686-45023500-4697-11ea-8a8c-740fa8cf3767.png">

2020-02-03 07:18 UTC, yuya-konkon commented
課題終わりました。
確認お願い致します。
<img width="952" alt="スクリーンショット 2020-02-03 16 18 25" src="https://user-images.githubusercontent.com/58411049/73633008-db872400-46a0-11ea-916a-3011db8f1dae.png">
<img width="952" alt="スクリーンショット 2020-02-03 16 18 20" src="https://user-images.githubusercontent.com/58411049/73633009-db872400-46a0-11ea-875e-19d1b66af216.png">

2020-02-04 04:00 UTC, Arisaarisa commented
細かいですがelseのインデントをifと合わせたらOKです！

![LGTM](https://lgtmoon.herokuapp.com/images/73573)

2020-02-04 07:59 UTC, Arisaarisa commented
https://lgtmoon.herokuapp.com/images/73607

2020-02-05 02:53 UTC, merged